# Generated by Django 2.1.2 on 2018-10-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='p_alta_estado',
            field=models.BooleanField(default=False, verbose_name='Alta del producto'),
        ),
    ]
