# Generated by Django 2.1.2 on 2018-10-03 20:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedor', '0001_initial'),
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleInventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('di_stock_logico', models.IntegerField(blank=True, null=True)),
                ('di_stock_fisico', models.IntegerField(blank=True, null=True)),
                ('di_variacion_stock', models.IntegerField(blank=True, null=True)),
                ('di_estado_concordancia', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleMovimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dm_activo', models.BooleanField(default=False)),
                ('dm_cant_solicitada', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('dm_cant_entrada', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('dm_cant_salida', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('dm_fecha_operacion', models.DateField(null=True)),
                ('dm_tipo', models.CharField(choices=[('1', 'Salida por Consumo'), ('2', 'Salida por ajuste de Inventario'), ('3', 'Salida por Traspaso'), ('4', 'Ingreso por Compra'), ('5', 'Ingreso por ajuste de Inventario'), ('6', 'Terminado')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='GuiaRemision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gr_fecha_envio', models.DateField()),
                ('gr_nro_guia_remision', models.CharField(max_length=15, unique=True)),
                ('gr_nombre_courier', models.CharField(max_length=150)),
                ('gr_destino', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Guia de Remisión',
                'verbose_name_plural': 'Guias de Remisión',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_fecha_inventario', models.DateTimeField(auto_now=True)),
                ('inv_estado', models.BooleanField(default=True, verbose_name='Estado del Inventario')),
                ('inv_observaciones', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mov_fecha_reg', models.DateTimeField(blank=True, null=True)),
                ('mov_estado', models.BooleanField(default=False, verbose_name='Activo')),
                ('mov_tipo', models.CharField(blank=True, choices=[('1', 'Salida por Consumo'), ('2', 'Salida por ajuste de Inventario'), ('3', 'Salida por Traspaso'), ('4', 'Ingreso por Compra'), ('5', 'Ingreso por ajuste de Inventario'), ('6', 'Terminado')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ot_codigo', models.CharField(max_length=15)),
                ('ot_fecha_pedido', models.DateTimeField(auto_now=True)),
                ('ot_kilometraje', models.PositiveIntegerField()),
                ('ot_estado', models.CharField(choices=[('1', 'En Proceso'), ('2', 'Cumplido'), ('3', 'Cumplido con retraso'), ('4', 'Cancelado')], default='1', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Padron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdn_numero', models.PositiveIntegerField()),
                ('pdn_placa', models.CharField(max_length=10)),
                ('pdn_estado', models.BooleanField(default=True)),
                ('pdn_kilometraje', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Padron',
                'verbose_name_plural': 'Padrones',
            },
        ),
        migrations.CreateModel(
            name='ParteIngreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pi_codigo', models.CharField(max_length=15)),
                ('fk_id_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.Movimiento')),
                ('fk_id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedor.Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stk_stock', models.IntegerField(blank=True, null=True)),
                ('stk_fecha_actualizacion', models.DateTimeField(blank=True)),
                ('fk_id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Producto')),
            ],
        ),
    ]
