# Generated by Django 2.1.2 on 2018-10-09 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('almacen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='fk_id_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Empleado'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='fk_id_movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.Movimiento'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='fk_id_padron',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.Padron'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='fk_id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='fk_id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guiaremision',
            name='fk_id_movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.Movimiento'),
        ),
        migrations.AddField(
            model_name='detallemovimiento',
            name='fk_id_movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.Movimiento'),
        ),
        migrations.AddField(
            model_name='detallemovimiento',
            name='fk_id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Producto'),
        ),
        migrations.AddField(
            model_name='detalleinventario',
            name='fk_id_inventario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.Inventario'),
        ),
        migrations.AddField(
            model_name='detalleinventario',
            name='fk_id_linea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.LineaProducto'),
        ),
        migrations.AddField(
            model_name='detalleinventario',
            name='fk_id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Producto'),
        ),
        migrations.AddField(
            model_name='detalleconfiabilidad',
            name='fk_id_inventario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.Inventario'),
        ),
        migrations.AddField(
            model_name='detalleconfiabilidad',
            name='linea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.LineaProducto'),
        ),
    ]
