# Generated by Django 2.1.2 on 2018-10-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_auto_20181009_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleconfiabilidad',
            name='confiabilidad',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
