# Generated by Django 2.1.2 on 2018-10-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0003_auto_20181009_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='inv_confiabilidad',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
