# Generated by Django 2.1.2 on 2018-10-10 22:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0004_auto_20181009_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleinventario',
            name='di_stock_fisico',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
