# Generated by Django 2.1.2 on 2018-10-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0005_auto_20181010_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='inv_observaciones',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
