# Generated by Django 2.1.2 on 2018-10-03 20:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)])),
                ('razon_social', models.CharField(max_length=150)),
                ('rep_legal', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message="El numero telefonico debe tener el formato: '+999999999'. hasta 12 digitos.", regex='^\\+?1?\\d{9,15}$')])),
                ('direccion', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
