# Generated by Django 2.1.2 on 2018-10-11 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='emp_estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='emp_telf',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message="El numero telefonico debe tener el formato: '+999999999'. hasta 12 digitos.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='emp_apellido',
            field=models.CharField(max_length=145),
        ),
    ]
